### ISSUE TITLE
add compiled file to install it via bower

### ISSUE THREAD

**Issue by lalop** [tellform/angular-tellform#1]

**Comment by whitef0x0** [comment]
We should probably move away from bower since it is deprecated.

**Comment by lalop** [comment]
bower is deprecated ????

**Comment by whitef0x0** [comment]
Yes. Read this https://medium.com/@nickheiner/why-my-team-uses-npm-instead-of-bower-eecfe1b9afcb#.vwvqn5jqd

**Comment by lalop** [comment]
I didn't know the bower issue since I only use npm ;)
But I never shared a js library before and using npm for that seems to make npm and a browserify ( or other require able tool ) mandatory for the end user.
Is that sound good for you ?

**Comment by whitef0x0** [comment]
@lalop I added bower support.
