### ISSUE TITLE
Is it updated ?

### ISSUE THREAD

**Issue by saurabhPV** [tellform/angular-tellform#13]
Is it in sync with tellform repo? if not can you please guide me  to do that?

**Comment by whitef0x0** [comment]
@saurabhPV not it is not currently in sync with the tellform repo. However it would be pretty easy to extract the form logic from tellform as it's completely seperated. You just need to copy public/form_modules as well as public/form_application.js and public/form_config.js

**Comment by saurabhPV** [comment]
ok thanks! I will try that!

**Comment by whitef0x0** [comment]
@saurabhPV you also need to include the bower dependencies in bower.json

**Comment by saurabhPV** [comment]
@whitef0x0  Thanks a lot!

1.I cloned the main repo deleted everything except public folder and bower.json. 
2.Then I copied grunt file.js, package.json,config, css, demo and publish.js. 
3. ran command bower install.  
4.ran command npm install grunt --save-dev (failed saying browserify-shim not found)
5.ran command npm install browserify browserify-shim
6.ran grunt 

It generates bundle.js , form.css ,form.js ,template.js in dist folder but not the lib folder. 
I don't  remember exactly how but I was able to generate the lib in angular-tellform repo.

**Comment by whitef0x0** [comment]
@saurabhPV you have to run bower install. Bower installation was removed from the npm script to maintain compatibility with the Heroku Button.

**Comment by saurabhPV** [comment]
Thanks!
But I end up using main Tellform repo instead.

**Comment by ianubhav** [comment]
Can you help me with the bundle.js if using directly the main repo? When I ran bower install in the tellform-repo and copied its libraries here I was getting some missing files errors

**Comment by saurabhPV** [comment]
@ianubhav Applogies for the delayed response.
I just checked my old repo I don't see any config changes I had done to run this. But I see I had added few new component and few fixes. Unfortunately I don't remember what changes we did to build, If you haven't fixed it let me know I will try to dig into the code and can find out what needs to be done.
