### ISSUE TITLE
remove field._id mandatory

### ISSUE THREAD

**Issue by lalop** [tellform/angular-tellform#5]
`field._id` should not be mandatory.
This is legacy from mongo and field index should do the work

**Comment by whitef0x0** [comment]
Are you referring to the field model?

**Comment by lalop** [comment]
In the form sended by tellform to angular, each field as an id  and the directives use it but identify the current field but the index could do this

**Comment by lalop** [comment]
Playing with the form library, `field._id` seems pretty usefull.
It's a kind of `input[name]`
