### ISSUE TITLE
Add support for multilingual form

### ISSUE THREAD

**Issue by lalop** [tellform/angular-tellform#7]
Since we can specify the form lang we should support translating static string.

**Comment by whitef0x0** [comment]
Yea. You can do the French translation?

**Comment by lalop** [comment]
It's done on my pr https://github.com/whitef0x0/tellform/pull/59/commits/e9cd5272fce5ea086ae4197b236fd1ddafded4a5

**Comment by whitef0x0** [comment]
@lalop can you add this to this module as well?

**Comment by lalop** [comment]
this is closed by the sync
